Algoritmo "PROVA -- Q.4"
Var
  nm: caractere
Inicio
  escreval ("============================================")
  escreval ("")
  escreval ("                  LOGIN                     ")
  escreval ("")
  escreval ("============================================")
  escreval ("")
  escreval ("")
  escreval ("Informe Seu Nome :")
  escreval ("")
  leia(nm)
  escreval ("")
  limpatela
  
  escreval ("Seja Bem Vindo(a)! ",nm," .")

Fimalgoritmo
