Algoritmo "PROVA -- Q.24"
Var
   psw:inteiro
Inicio
   escreval ("=========================================")
   escreval ("")
   escreval ("               Ubuntu                      ")
   escreval ("")
   escreval ("=========================================")
   escreval ("")
   repita
   escreval ("Informe A senha De JoaoPedro Para Acessa-lo")
   escreval ("")
   leia(psw)
   ate (psw = 1234)
   limpatela
   
   escreval ("Bem Vindo JoaoPedro !")
   
   
Fimalgoritmo
