Algoritmo "PROVA -- Q.20"
Var
  i:inteiro
Inicio
 escreval("----------------------------------------------------")
 escreval("")
 escreval("           Os Numeros Pares entre 1 e 50                      ")
 escreval("")
 escreval("-----------------------------------------------------")

   para i de 1 ate 50 faca
   se (i % 2 = 0) entao
   escreva(i:4)
   fimse
   fimpara
Fimalgoritmo
