Algoritmo "PROVA -- Q.24"
Var
  cont1, cont2, cont3, cont, cont4, cont5, cont6, num:inteiro
Inicio
cont <- 0
cont1 <- 1
cont2 <- 1
  escreval ("WMWMWMWMWWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
  escreval("")
  escrevaL("        SEQUENCIA DE FIBONACCI COM ENQUANTO                   ")
  escreval("")
  escreval("WMWMWMWMWWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM")
  escreval("")
   escreval ("Qual O Numero Limite Da Sequencia?")
   escreval("")
   leia(num)
   escreval("")
  enquanto (cont2 <= num)faca
  escreval (cont)
    cont3 <- cont + cont1
    cont <- cont1
    cont1 <- cont3
    cont2 <- cont2 + 1

   fimenquanto
Fimalgoritmo
